[build]
builder = "NIXPACKS"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput --clear"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn weather_dashboard.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.10.11"
PYTHONUNBUFFERED = "1" 