[build]
builder = "NIXPACKS"
buildCommand = "python -m pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn weather_dashboard.wsgi"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[env]
PYTHON_VERSION = "3.10.11" 